language: java

# Those lines enable using openjdk9
# See https://github.com/travis-ci/travis-ci/issues/5520
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - jdk: openjdk7
      env: TEST_GRADLE_VERSIONS=3.4
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.5
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.6
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.7
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.8
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.9
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.10
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.11
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.12
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.13
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.14
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=3.0
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=3.1
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=3.2
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=3.4
    - jdk: oraclejdk9
      env: TEST_GRADLE_VERSIONS=3.4
  allow_failures:
    - jdk: oraclejdk9
install: true
script: ./gradlew build -Ptest.gradle-versions="$TEST_GRADLE_VERSIONS"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
